### ISSUE TITLE
Add ListView Builder of Todo widget 

### ISSUE THREAD

**Issue by auspicious123** [gani2267/todoapp_sqlitedb#1]
Add ListView Builder of Todo widget which will be milestone of task it's that type of code you have commented . I checked it my uncommiting but I got overflow error.

**Comment by gani2267** [comment]
It's just added by me in new release. Please check new release 1.0.1 
It is actually patch fix for Todo widget.
That functionality is now present in new release.
Please try it out.
![Screenshot_2022-07-27-01-54-47-66_a97868f80539cb8c4d96ddcc089a6162](https://user-images.githubusercontent.com/84265879/181105350-c0a16a47-63d0-45c5-8fe1-641dca193cf7.jpg)
